ALLCLASSFILES = CIRRWindow.class \
                Display.class \
                GetRequest.class \
                IRRj.class \
                IRRWindow.class \
                MailWindow.class\
		GeneralErrorWindow.class\
		OptionsMenu.class\
		redLabel.class

