#
# $Id: Makefile,v 1.2 2001/07/13 18:02:41 ljb Exp $
#

include ../../Make.include

OBJS    = util.o prefix.o mrt.o user.o schedule.o \
	  alist.o trace.o select.o connect.o reboot.o user_old.o user_util.o \
	  compat.o buffer.o
ARCHIVE = $(MRTLIB)

include ../Make.include

# DO NOT DELETE THIS LINE -- make depend depends on it.
