#!/usr/bin/env bash
VERSION=$1

DATE=$(date +%Y%m%d)

sed "s/@@version@@/$VERSION/" build-scripts/rpm/irrd.spectemplate > build-scripts/rpm/irrd.spec
sed -i.bak "s/@@date@@/${DATE}/" src/configure.in
sed -i.bak "s/@@IRRD_VERSION@@/${VERSION} [$(date +%d%b%Y)]/" src/include/version.h
