#
# $Id: Makefile,v 1.2 2001/07/13 18:02:24 ljb Exp $
#

include ../../Make.include

OBJS    = config_file.o 
ARCHIVE = $(CFGLIB)

include ../Make.include

# DO NOT DELETE THIS LINE -- make depend depends on it.
