/* include/config.h.  Generated by configure.  */
/* include/config.h.in.  Generated automatically from configure.in by autoheader.  */
/*
 * $Id: config.h.in,v 1.10 2001/12/03 20:08:16 ljb Exp $
 */


/* Define if using alloca.c.  */
/* #undef C_ALLOCA */

/* Define to empty if the keyword does not work.  */
/* #undef const */

/* Define to one of _getb67, GETB67, getb67 for Cray-2 and Cray-YMP systems.
   This function is required for alloca.c support on those systems.  */
/* #undef CRAY_STACKSEG_END */

/* Define if you have alloca, as a function or macro.  */
#define HAVE_ALLOCA 1

/* Define if you have <alloca.h> and it should be used (not on Ultrix).  */
#define HAVE_ALLOCA_H 1

/* Define if the `setpgrp' function takes no argument.  */
#define SETPGRP_VOID 1

/* If using the C implementation of alloca, define if you know the
   direction of stack growth for your system; otherwise it will be
   automatically deduced at run-time.
 STACK_DIRECTION > 0 => grows toward higher addresses
 STACK_DIRECTION < 0 => grows toward lower addresses
 STACK_DIRECTION = 0 => direction of growth unknown
 */
/* #undef STACK_DIRECTION */

/* Define if you have the ANSI C header files.  */
#define STDC_HEADERS 1

/* Define if you can safely include both <sys/time.h> and <time.h>.  */
#define TIME_WITH_SYS_TIME 1

/* Define if your <sys/time.h> declares struct tm.  */
/* #undef TM_IN_SYS_TIME */

/* Define if you have struct in6_addr */
#define HAVE_STRUCT_IN6_ADDR 1

/* Define if you have pthread library (-lpthread) */
#define HAVE_LIBPTHREAD 1

/* Define if you have pthread_attr_setscope */
#define HAVE_PTHREAD_ATTR_SETSCOPE 1

/* Define if you have u_char, u_int, u_short, and u_long */
#define HAVE_U_TYPES 1

/* Define if socklen_t absent */
/* #undef socklen_t */

#define HAVE_MAIL 1

#define HAVE_SENDMAIL 1

#define PGP 1

#define HAVE_GZIP 1

/* #undef HAVE_IRRDCACHER */

#define HAVE_WGET 1

/* Define if you have the gethostbyaddr_r function.  */
#define HAVE_GETHOSTBYADDR_R 1

/* Define if you have the gethostbyname_r function.  */
#define HAVE_GETHOSTBYNAME_R 1

/* Define if you have the inet_ntop function.  */
#define HAVE_INET_NTOP 1

/* Define if you have the declaration for the inet_ntop function.  */
#define HAVE_DECL_INET_NTOP 1

/* Define if you have the localtime_r function.  */
#define HAVE_LOCALTIME_R 1

/* Define if you have the memmove function.  */
#define HAVE_MEMMOVE 1

/* Define if you have the setsid function.  */
#define HAVE_SETSID 1

/* Define if you have the sigaction function.  */
#define HAVE_SIGACTION 1

/* Define if you have the sigprocmask function.  */
#define HAVE_SIGPROCMASK 1

/* Define if you have the sigset function.  */
#define HAVE_SIGSET 1

/* Define if you have the strerror function.  */
#define HAVE_STRERROR 1

/* Define if you have the strtok_r function.  */
#define HAVE_STRTOK_R 1

/* Define if you have the mkstemp function.  */
#define HAVE_MKSTEMP 1

/* Define if you have the declaration for the mkstemp function.  */
#define HAVE_DECL_MKSTEMP 1

/* Define if you have the mkdtemp function.  */
#define HAVE_MKDTEMP 1

/* Define if you have the declaration for the mkdtemp function.  */
#define HAVE_DECL_MKDTEMP 1

/* Define if you have the declaration for the getdtablesize function.  */
#define HAVE_DECL_GETDTABLESIZE 1

/* Define if you have the declaration for the utimes function.  */
#define HAVE_DECL_UTIMES 1

/* Define if you have the snprintf function.  */
#define HAVE_SNPRINTF 1

/* Define if you have the dirname function.  */
#define HAVE_DIRNAME 1

/* Define if you have the basename function.  */
#define HAVE_BASENAME 1

/* Define if you have the thr_setconcurrency function.  */
/* #undef HAVE_THR_SETCONCURRENCY */

/* Define if you have the <pthread.h> header file.  */
#define HAVE_PTHREAD_H 1

/* Define if you have the <resolv.h> header file.  */
/* #undef HAVE_RESOLV_H */

/* Define if you have the <string.h> header file.  */
#define HAVE_STRING_H 1

/* Define if you have the <strings.h> header file.  */
#define HAVE_STRINGS_H 1

/* Define if you have the <libgen.h> header file.  */
#define HAVE_LIBGEN_H 1

/* Define if you have the <sys/select.h> header file.  */
#define HAVE_SYS_SELECT_H 1

/* Define if you have the <sys/stropts.h> header file.  */
#define HAVE_SYS_STROPTS_H 1

/* Define if you have the <sys/time.h> header file.  */
#define HAVE_SYS_TIME_H 1
